import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "./components/header";
import C_gallery from "./components/c_gallery";
import Foto from "./components/foto";
import Footer from "./components/footer";
import Script from "next/script";


export default function Gallery() {
  return (
    <div>
      <Head>
        <title>smpiainulhuda</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/apple-icon-57x57.png" />
        <script type="text/javascript" src="../styles/js/main.js"></script>
      </Head>
      <Header />
      <C_gallery />
      <Foto/>
      <Footer />
    </div>
  );
}
