import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "./components/header";
import Content from "./components/content";
import Footer from "./components/footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>smpiainulhuda</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/apple-icon-57x57.png" />
        <script type="text/javascript" src="../styles/js/main.js"></script>
      </Head>
      <Header />
      <Content />
      <Footer />
    </div>
  );
}
