import Head from "next/head";
import Header from "./components/header";
import Footer from "./components/footer";
import Ppdb from "./components/ppdb";

export default function about() {
  return (
    <div>
      <Head>
        <title>smpiainulhuda</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/apple-icon-57x57.png" />
      </Head>
      <Header />
      <Ppdb />
      <Footer/>
    </div>
  );
}